### ISSUE TITLE
multicast with default impl?

### ISSUE THREAD

**Issue by questor** [iboB/dynamix#29]
I'm experimenting with your library and I like the design. But I've come across an error in my editor implementation and I'm not sure how to handle that.

Basically I have a basic object in which I can add mixins. And I have multicast messages for different purposes (showing gui stuff for example). Now when I create a new (empty) object and send a multicast message I get a "bad_message_call" exception because the object has no mixins in the initial state. Should I add a "default" mixin with empty implementations, is there something similar to default-implementation for multicast messages or should it be allowed to send multicast messages to empty objects?

**Comment by questor** [comment]
workaround for now: check if the object implements the feature, but I would have expected that multicast messages are more like pub-sub, so sending a multicast message to an object should be successful, even if the object doesn't listen to the multicast message (yet). Am I wrong with my assumption?

**Comment by iboB** [comment]
Currently what you observe is the designed behavior. If the object doesn't implement a message, even if it's a multicast, calling it throws `bad_message_call`. You've spotted one way to circumvent this and it's by checking with implements. You anticipated the other way, even though it's poorly documented. Messages can have default implementations. You can check out the [messages tutorial](https://ibob.github.io/dynamix/tutorials.html#messages) to see how that works (the example is towards the end).

Of course you can also change your version of the library to suit this need. In `message_macros.hpp` you can comment out lines 126, 127, 171, and 172 and multicasts will silently do nothing when there is no mixin implementing them.

I don't think making this the default library behavior is the way to go, but it seems it's a good idea to make it optional, and I'll do so for the next release

**Comment by questor** [comment]
okay, thanks for the answer (and thanks for open sourcing this library! look really neat and to the point for gamedev stuff)
