### ISSUE TITLE
Logo Prosal for Dynamix

### ISSUE THREAD

**Issue by area55git** [iboB/dynamix#31]
Hi @iboB, I'm a graphic designer and I like to collaborate with open source projects. Do you know that the graphic image of a project is very important? thinking about it I would like to design a logo for your Project Dynamix.

I will be pleased to collaborate with you.

**Comment by iboB** [comment]
This sounds great! Thanks!

The thought has crossed my mind multiple times and I intended to design something myself, but I don't have any ideas. It would be great if someone who actually knows what they're doing is on it.

You should know that the library's name is stylized as DynaMix (capital M inside).

**Comment by area55git** [comment]
Great, do you have any suggestions to start with the sketches?

**Comment by iboB** [comment]
This is a list of my thoughts. I don't know what could look good as a logo

1. DynaMix helps you create objects out of building blocks / components. So some direction could be a toy of sorts made out of interlocking bricks (much like Lego bricks)
   * Perhaps something simple like this: http://bloggedd.com/wordpress/wp-content/uploads/2012/12/lego-brick-tiny-camera-2.jpg
   * Or instructions this: https://ideascdn.lego.com/community/projects/bcf/2c9/148803/2576042-o_1aoiphmkv1s0b7sr1c6to4713h3m-thumbnail-full.png
   * Or something fancy like a ship with wheels or a car with wings
2. On the same direction something more abstract can be chosen. DynaMix is heavily influenced from Smalltalk. This implementation of Smalltalk has a nice logo: https://c1.staticflickr.com/4/3633/3507816245_f272627c2f.jpg Using regular cubes (building blocks) to build an abstract shape
3. Combining different mixins produces different objects. So something obviously cobbled together might also work. Again I have no idea what could work. I mentioned a ship with wheels, a car with wingts, a half airplane-half car, some mytical creature like a centaur or a griffin, or Pegasus?... I fear a lot of these might look silly.

Perhaps you can think of something entirely different. Here are some sentences which you might want to use for an inspiration (of course you don't have make use of ALL of them!)

* Combine components into objects.
* Modify/Mutate living/existing objects (Random thought: mutate is an actual functionality of the library. Mutate could be a direction)
* Create and change interfaces 

That's a lot, but I've been thinking about this for a long time :)

**Comment by iboB** [comment]
Perhaps something out of this list might work as a logo as well: https://en.wikipedia.org/wiki/Category:Mythological_hybrids

**Comment by area55git** [comment]
Wow, very interesting your suggestions, I'll start with the sketches.

**Comment by area55git** [comment]
Hello @iboB , I'm working on the sketches, I have 2 ideas, a modern one made with cubes and the other is an abstract mythological griffin

![logo proposal for dinamix 1](https://user-images.githubusercontent.com/38330420/43967889-98b83226-9c93-11e8-9d16-a7bd18345419.jpg)

Remember that they are sketches, you can suggest any change

**Comment by area55git** [comment]
You can see several color options

![logo proposal for dinamix 1](https://user-images.githubusercontent.com/38330420/44044556-ee05e7c0-9ef3-11e8-8a24-6fede4ffb7cb.jpg)

What color selection do you like?

**Comment by iboB** [comment]
Great! Thanks!

I like the purple one and the blue one. But I can't decide... so, let's go with the blue one :)

Now I realize that fixing library name makes the text unbalanced (with the wrong name the 'A' could be the centerpiece of the text and it aligned nicely under the logo. The correct name makes this impossible). Can you please try some other alignments of the text and logo. Perhaps we can try a font which is not all-caps and have the stylized name "DynaMix". Here is a small experiment of mine:

![text to the right](https://i.imgur.com/PlDA8lb.png)

Perhaps a better font can be chosen or another alignment...

**Comment by area55git** [comment]
Your suggestion seems perfect @iboB, these are the results using several types of font, in some I put the normal text combined with bold.

![logo proposal for dinamix 1](https://user-images.githubusercontent.com/38330420/44093040-3e80ebbc-9fa0-11e8-8576-6004f974a7f4.jpg)

**Comment by iboB** [comment]
Thanks!

I'll have to go with the first variant (the all-caps font with enlarged letters). It has hard angles and edges and fits the logo better, I think.

One last request. Can we experiment with making the lighter colors a bit darker? If you don't have time I can do it myself. If you make a pull request with an svg of the logo (just add it to a subdirectory in doc `doc/logo`), I can take ti from there. I'll make some more color experiments and add it to the docs and the README.

Just tell me what license the logo has and how you want to be credited.

**Comment by area55git** [comment]
Perfect I will prepare the files in SVG and make a PR.
Just by placing the logos in the doc folder and one in the Readme folder is enough for me, you could add a mention about my collaboration.

I can also place the logos in a Googledrive link.

This work is licensed under a Creative Commons Attribution 4.0 International License.
![derechos](https://user-images.githubusercontent.com/38330420/44161563-b60cf180-a08b-11e8-9269-2dbc63d848b1.jpg)

**Comment by area55git** [comment]
This is the construction of the final logo with exact measurements and proportions. You like it like that?

![logo dynamix](https://user-images.githubusercontent.com/38330420/44214755-e06bb700-a13e-11e8-8826-ac088acc3eb0.jpg)

**Comment by iboB** [comment]
That's perfect! Thanks!

**Comment by iboB** [comment]
Thanks. I like the first one - with the grey background - better.

**Comment by area55git** [comment]
Bo am new to github, how can I create the "Logo" folder inside the Doc folder?

**Comment by area55git** [comment]
[DynaMix Logos](https://drive.google.com/open?id=1-Jn3fHaR2ZSv7X3r4S9m0ptXEqykJ3no)

In this link are the logos in various formats (SVG, PNG, PDF, EPS)

**Comment by area55git** [comment]
This is the color palette

![paleta](https://user-images.githubusercontent.com/38330420/44233507-078fac00-a172-11e8-83a6-dff75d976454.jpg)

**Comment by iboB** [comment]
Awesome! Thanks!

Last question:

I'll add this to the README "The DynaMix logo is licensed under a Creative Commons Attribution 4.0 International License. Copyright &copy; 2018 XXXXXXX ". So, do you want to be credited as "area55git" or as a name?

**Comment by area55git** [comment]
Hi @iboB my name is Francisco. I like that you credit me with **[@area55git](https://github.com/area55git)**
